# https://github.com/awesome-containers/static-bash
ARG STATIC_BASH_VERSION=5.2.15
ARG STATIC_BASH_IMAGE=ghcr.io/awesome-containers/static-bash

# https://github.com/awesome-containers/static-openssl
ARG STATIC_OPENSSL_VERSION=3.1.0
ARG STATIC_OPENSSL_IMAGE=ghcr.io/awesome-containers/static-openssl

# https://github.com/awesome-containers/alpine-build-essential
ARG BUILD_ESSENTIAL_VERSION=3.17
ARG BUILD_ESSENTIAL_IMAGE=ghcr.io/awesome-containers/alpine-build-essential


FROM $STATIC_BASH_IMAGE:$STATIC_BASH_VERSION-slim AS static-bash
FROM $STATIC_OPENSSL_IMAGE:$STATIC_OPENSSL_VERSION AS static-openssl
FROM $BUILD_ESSENTIAL_IMAGE:$BUILD_ESSENTIAL_VERSION AS build

WORKDIR /src/openssl
COPY --from=static-openssl /bin/openssl ./

RUN set -xeu; \
    upx --no-progress --no-color openssl; \
    upx -t --no-progress --no-color openssl; \
    ! ldd openssl && :; \
    chmod -cR 755 openssl; \
    chown -cR 0:0 openssl; \
    ./openssl version

# slim static openssl image
FROM static-bash

COPY --from=build /src/openssl/openssl /bin/openssl
ENV OPENSSL_CONF=/etc/openssl.cnf
COPY --from=static-openssl /etc/openssl.cnf /etc/openssl.cnf
ENV SSL_CERT_DIR=/etc/ssl/certs
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
